"""Add first name and last name to user

Revision ID: 0af3362e5fe8
Revises: 13b57e060a12
Create Date: 2024-04-11 10:13:51.367078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.common.models
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0af3362e5fe8'
down_revision: Union[str, None] = '13b57e060a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
