name: Vue - Lint and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        working-directory: ./vue
        run: bun install
      - name: Lint
        working-directory: ./vue
        run: bun run lint
      - name: Format
        working-directory: ./vue
        run: bun run format

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        working-directory: ./vue
        run: bun install
      - name: Unit Test
        working-directory: ./vue
        run: bun run test:unit:nowatch

